
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/marry?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
  thymeleaf:
    cache: false
    mode: HTML5
  http:
    encoding:
      charset: UTF-8
#    prefix: /templates/
#    suffix: .html
mybatis:
  type-aliases-package: com.mk.onevone.entity
  mapper-locations: classpath:/mappers/*Mapper.xml
  config-location: classpath:/mybatis-config.xml
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    pageSizeZero: 0
    returnPageInfo: always
server:
  context-path: /
qiniu:
  AK: iPBVbNYwFb_7M5GOHYFjTFEkcsDqMomFbRVA95tt
  SK: UJjluq3LsyqQYwF9192pYFFDCl0bITqykZqggzHd
  bucket: onevone
multipart:
  maxFileSize: 10Mb
  maxRequestSize: 100Mb